# Generated by Django 4.2.2 on 2023-06-23 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Task name')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date create')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date update')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_tasks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'UserTask',
                'verbose_name_plural': 'UserTasks',
                'db_table': 'DJ_user_task',
                'ordering': ['-date_update', '-date_create'],
            },
        ),
    ]
