# Generated by Django 4.2.2 on 2023-06-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='archive',
            field=models.BooleanField(default=0, verbose_name='Completed'),
        ),
    ]
